### ISSUE TITLE
Invalid Syntax when trying to run the first time

### ISSUE THREAD

**Issue by GonrasK** [eps696/aphantasia#26] opened 2021-08-20 07:00 UTC
I followed all the instructions and still I'm getting this error - 

```
aphantasia git:(master) python clip_fft.py -t "the text" --size 1280-720 
  File "clip_fft.py", line 112
    Ys = [torch.randn(*Y.shape).cuda() for Y in [Yl_in, *Yh_in]]
```

**Comment by eps696** [comment] 2021-08-20 08:50
1) please always quote _full_ error log, from the start till the end. it's impossible to tell what's wrong from such cut (it doesn't even include error message).
2) i cannot reproduce it here - the mentioned command runs without problems. 
besides, line 112 belongs to the function for DWT-based generation, which is used if explicitly set `--dwt` (not presented in your command). so it seems something is corrupt or edited on your side. try downloading fresh repo again; if the problem persists, let's check your actions step by step.

**Comment by GonrasK** [comment] 2021-08-20 09:14
1. It was the full error log.. I'm attaching a screenshot as well
<img width="653" alt="Screen Shot 2021-08-20 at 12 10 39" src="https://user-images.githubusercontent.com/30444072/130210193-06a970d6-e2c5-430a-b2e9-ff6a13bd3b9d.png">


2. I reproduces all the steps in the README and I'm still getting the same error.

**Comment by eps696** [comment] 2021-08-20 13:02
no it wasn't - you dropped the most important part about _syntax_ error. 

what is your python version? the repo is supported on 3.7. if might also work on 3.5, but i can't check that. older versions are definitely out of scope.

**Comment by GonrasK** [comment] 2021-08-20 14:29
You are definitely right. Python was outdated. But now I have a different problem - 

```
➜  aphantasia git:(master) sudo python3 clip_fft.py -t "the text" --size 1280-720      

 using model ViT-B/32
 topic text:  the text
Traceback (most recent call last):
  File "clip_fft.py", line 470, in <module>
    main()
  File "clip_fft.py", line 394, in main
    txt_enc = enc_text(a.in_txt)
  File "clip_fft.py", line 372, in enc_text
    emb = model_clip.encode_text(clip.tokenize(txt).cuda())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

Isn't it possible to run it with CPU only even though I installed pytorch with CPU support?

**Comment by eps696** [comment] 2021-08-20 21:13
no way.. 
in theory it would work, but soo prohibitively slow, it just doesn't make any sense 
use colab, if you're out of local resources

**Comment by eps696** [comment] 2021-08-31 19:15
i presume, the question is answered now, so i'm closing the issue. feel free to reopen it if needed (or start a new one in case of different problem).

**Closed by eps696** 2021-08-31 19:15 UTC

**Comment by wanghaisheng** [comment] 2021-12-09 19:43
@eps696  how to make it happen without a nvidia  gpu

```
(base) wenke@wenkedeMac-mini aphantasia % python clip_fft.py -t "greate wall" --size 1280-720    

Traceback (most recent call last):
  File "clip_fft.py", line 477, in <module>
    main()
  File "clip_fft.py", line 304, in main
    params, image_f, sz = fft_image(shape, 0.01, a.decay, a.resume)
  File "clip_fft.py", line 225, in fft_image
    params, size = resume_fft(resume, shape, decay_power, sd=sd)
  File "clip_fft.py", line 205, in resume_fft
    params = 0.01 * torch.randn(*params_shape).cuda()
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 208, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by eps696** [comment] 2021-12-09 20:16
@wanghaisheng quick answer: no way.
longer answer: while this may be possible in theory, cpu-only processing should be prohibitively slow, so it doesn't make sense for me to invest any time to prove that.

**Comment by wanghaisheng** [comment] 2021-12-10 04:01
what about amd gpu ?@eps696

**Comment by eps696** [comment] 2021-12-10 09:31
no way either. most current neural libraries (including those used here) use cuda on nvidia.
as far as i know, it may be possible to port it somehow on top of opencl platform for amd, but that's totally out of scope for such repo. use colab instead.
