### ISSUE TITLE
How do you upload a photo to work with it?

### ISSUE THREAD

**Issue by raul2297** [eps696/aphantasia#20] opened 2021-05-01 18:23 UTC
NameError                                 Traceback (most recent call last)
<ipython-input-2-791d42c4b984> in <module>()
     12   text = translator.translate(text, dest='en').text
     13 if upload_image:
---> 14   uploaded = files.upload()

NameError: name 'files' is not defined

**Comment by eps696** [comment] 2021-05-04 22:49
1) please mention the notebook or script, which gave the error - it's not always obvious, there are few of them in the repo. 
2) it seems you didn't run "General setup" cell. It must precede any other command, and should be run again after every runtime restart.

**Comment by raul2297** [comment] 2021-05-04 23:55
*I am using it from colab Aphantasia.ipynb*

MessageError Traceback (most recent call last)

<ipython-input-2-c2e4ffc97399> <https://localhost:8080/#> in
<module>()     12   text = translator.translate(text, dest='en').text
   13 if upload_image:
---> 14   uploaded = files.upload()


------------------------------
2 frames
------------------------------

/usr/local/lib/python3.7/dist-packages/google/colab/_message.py
<https://localhost:8080/#> in read_reply_from_input(message_id,
timeout_sec)    104         reply.get('colab_msg_id') == message_id):
  105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])    107       return
reply.get('data', None)    108

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined

**Comment by eps696** [comment] 2021-05-05 15:05
please describe exact steps which have led to this (pressed buttons, typed entries, selected options, etc.).
i cannot reproduce it on my side.

**Comment by eps696** [comment] 2021-05-15 23:18
i presume you solved this (most probably just missed loading image with temporary button - that's a drawback of colab pipeline), so closing the issue. feel free to reopen it (with supplying more details), if the problem persists.

**Closed by eps696** 2021-05-15 23:18 UTC
